# Header
menu:
  Archives: archives
rss: atom.xml
title: Blog

author: rongying
aboutme: just a plebeian

# Content
excerpt_link: Read More...
fancybox: true
date_format: 'YYYY-MM-DD'

socials:
  github: "https://github.com/kohrongying"
  email: "kohrongying@gmail.com"

# Sidebar
# sidebar: right
# widgets:
# - category
# - tag
# - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

#主题方案
highlight_theme: atom light

# widget behavior
archive_type: 'monthly'
show_count: false

disqus_shortname:

# Miscellaneous
google_analytics: 'UA-109820124-3'
favicon: images/favicon.ico
avatar: "images/avatar.jpeg"
twitter:
fb_admins:
fb_app_id:
